# -*- coding: utf-8 -*-
"""Cyber210_Final_VulnAgent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bx1N-ID4RkBt-aJwTz0fhhA9s7xgq1eY
"""

import os
from dotenv import load_dotenv
# install dependencies
installs = ["pip install langchain_core langchain_openai python-dotenv langgraph httpx typing","pip install --quiet langchain","pip install --upgrade --quiet  langchain-google-genai pillow","pip install --quiet langchain-google-genai","pip install requests beautifulsoup4","pip install libgraphviz-dev","pip install pygraphviz"]
def installScript(installs):
	for pkg in installs:
		print(f"pkg: {pkg}")
		res = os.popen(pkg).read()
		print(res)
	print("\n\nDone installing\n")

installScript(installs)

apikey = os.environ["OPENAI_API_KEY"]
print("apikey: ", apikey)

#from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_openai import ChatOpenAI
from langgraph.graph import StateGraph, END
from typing import TypedDict, Annotated, List
import operator
from langgraph.checkpoint.sqlite import SqliteSaver
from langchain_core.messages import AnyMessage, SystemMessage, HumanMessage, AIMessage, ChatMessage
#from langchain.output_parsers import StructuredOutputParser
import os
import getpass
import re
import requests
from bs4 import BeautifulSoup

from langchain import PromptTemplate
#from langchain.document_loaders import WebBaseLoader
from langchain.schema import StrOutputParser
from langchain.schema.prompt_template import format_document

